### PR TITLE
FIX: Fix test failures

### PR DESCRIPTION
**Pull request by GuySartorelli**

### CODE REVIEW

**Comment by GuySartorelli** [comment]
Hmm... so the PHPCS test fails if there's no visibility, but the unit tests for PHP5.6 and 7.0 fail if there IS visibility....
Anyone got any thoughts for how to handle this?

**Comment by GuySartorelli** [comment]
Given that Silverstripe is dropping support for php <7.3 I'm inclined to just update the travis config to stop testing the unsupported php versions.

**Comment by maxime-rainville** [comment]
Do you want to update the Travis config to remove PHP 5.6 to 7.2 and replace them with 7.4 and 8.0?

**Comment by GuySartorelli** [comment]
@maxime-rainville Done in #22

**Comment by GuySartorelli** [comment]
I've done the work from #22 here now, since that will hopefully actually give passing tests so we can have confidence before merging. I'll close #22.

**Comment by GuySartorelli** [comment]
I'm honestly not sure why coverage worked this time but I'm not gonna question it. @maxime-rainville Tests are passing finally 😅

**Review by robbieaverill — APPROVED** [review]

**Comment by GuySartorelli** [comment]
Self-merging as it was approved by a core-committer and resolves issues that are blocking other PRs.

**Pull request merged**
